server:
  servlet:
    context-path: /hello
  port: 8080

# \u65E5\u5FD7
logging:
  level:
    com:
      example:
        SpringBoot: trace

# \u65E5\u5FD7\u5199\u5230\u6587\u4EF6\u4E2D
  file:
    name:
# \u65E5\u5FD7\u6587\u4EF6\u6700\u5927\u5185\u5B58\u8BBE\u7F6E
  logback:
    rollingpolicy:
      max-file-size: 5KB

